### ISSUE TITLE
Doesn't solve real problem

### ISSUE THREAD

**Issue by zelcode** [clickstorm/cs_file_meta_fill#1]
Hi,

there are similar extensions*, but I think neither solve the real problem, metadata should be filled on upload when you have real file name (not sanitized), so this should be solved before problem happens, not after that.

e.g. file for upload:
München Säbener Straße Ribéry.doc

filename after upload (sanitized):
Muenchen_Saebener_Strasse_Ribery.doc

then Fluent function tries to restore sanitized and damaged filename:
Muenchen Saebener Strasse Ribery.doc

The difference is clear, so metadata should be this:
**München Säbener Straße Ribéry**

and not this:
Muenchen Saebener Strasse Ribery

I have a case where editors upload several documents with filenames of 2-10 words and proper names. It would be crazy to ask them to manually fill metadata title.

I am not ext developer, but I found a way to hack the Core with (my) needed functionality, but ext solution will be much better.

*Similar ext:
https://extensions.typo3.org/extension/dd_filename2title/

In ext:media there is function:
https://github.com/fabarea/media/blob/master/Classes/Index/TitleMetadataExtractor.php

Regards

**Comment by PascaleBeier** [comment]
Hey,

This would be a nice addition, thanks for your Feedback! I will take a look.

**Comment by PascaleBeier** [comment]
Please see https://github.com/clickstorm/cs_file_meta_fill//compare/v1.0.1...v1.1.0

**Comment by zelcode** [comment]
Hi,

works great, but only for image file types, if you upload .doc file nothing happens.

**Comment by PascaleBeier** [comment]
Hey,

Please open a separate issue with steps to reproduce this 🙂
